comboRobot:
  youbot_hw_interface:
    hardware_interface:
      wheels:
        - wheel_joint_fl
        - wheel_joint_fr
        - wheel_joint_bl
        - wheel_joint_br

  dynamixel_control:
    hardware_interface:
      servos:
        - arm_0_1
        - arm_1_2
        - arm_2_3
        - arm_3_4
        - arm_4_5

  controller:

    youbot_controllers:
      youbot_state:
        type: joint_state_controller/JointStateController
        publish_rate: 50
        joints:
          - wheel_joint_bl
          - wheel_joint_br
          - wheel_joint_fl
          - wheel_joint_fr

      arm_state:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    vel_controller_fl:
      type: velocity_controllers/JointVelocityController
      joint: wheel_joint_fl
    vel_controller_fr:
      type: velocity_controllers/JointVelocityController
      joint: wheel_joint_fr
    vel_controller_bl:
      type: velocity_controllers/JointVelocityController
      joint: wheel_joint_bl
    vel_controller_br:
      type: velocity_controllers/JointVelocityController
      joint: wheel_joint_br
